-- create database customer_behaviorss;
use customer_behaviorss;
create table customer(
	customer_id INT, 
    age INT, 
    gender VARCHAR(10), 
    item_purchased VARCHAR(100), 
    category VARCHAR(100),
	purchase_amount INT,
	location VARCHAR(100), 
    size VARCHAR(10), 
    color VARCHAR(10), 
    season VARCHAR(100),
	review_rating FLOAT, 
    subscription_status VARCHAR(100), 
    shipping_type VARCHAR(100),
	discount_applied VARCHAR(100), 
    previous_purchases INT, 
    payment_method VARCHAR(100),
	frequency_of_purchases VARCHAR(100), 
    age_group VARCHAR(100), 
    purchase_frequency_days INT
)

-- what is the total revenue generated by male vs female customers
SELECT gender, sum(purchase_amount) as revenue from customer
GROUP BY gender;

-- which customer used a discount but still spend more than the average purchase amount
SELECT * from customer 
WHERE discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- which are the top 5 products with highest average review rating
select item_purchased as product, round(avg(review_rating)) as average_product_rating  from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- compare the average purchase amounts beween standard and express shiping
select shipping_type, round(avg(purchase_amount)) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subsscribers and non subscribers
select subscription_status as Subscribed, COUNT(customer_id) as customer_count, round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue from customer
group by subscription_status;

-- which 5 products have the highest percentage of purchases with discounts_applied?
select item_purchased
from customer
where discount_applied = 'Yes'
group by item_purchased
order by (count(item_purchased)/(select count(item_purchased) from customer))*100 desc
limit 5;

-- segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT customer_segment, count(*) as number_of_customers FROM customer_type
group by customer_segment;

-- what are top 3 most purchased product withing each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_counts
where item_rank <=3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;

